"""Add visit_count and max_visits columns to links

Revision ID: 5e857620fbd4
Revises: 5a96c7b5f82a
Create Date: 2024-10-30 01:57:25.449720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e857620fbd4'
down_revision = '5a96c7b5f82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('visit_count', sa.Integer(), nullable=True))
    op.add_column('links', sa.Column('max_visits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'max_visits')
    op.drop_column('links', 'visit_count')
    # ### end Alembic commands ###
